version: '3.0'

services:
  cleezy2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ:"Europe/Berlin"
    volumes:
      - ./:/usr/src/app
    restart: unless-stopped
